In [75]:
### Уровень 1 
import pandas as pd
df = pd.read_csv('C:\\Users\\User\\Documents\\ДЗ\\train.csv') 
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [76]:
df[df['Sex'] == 'male']['Survived'].mean()*100## процент выживших мужчин.

np.float64(18.890814558058924)

In [77]:
df['Age'].fillna(df.groupby(['Pclass', 'Sex'])['Age'].transform('median'))

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    21.5
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [78]:
pa=(df['Survived']==1).mean()## pa - вероятность выживания
pa

np.float64(0.3838383838383838)

In [79]:
pa2=(df['Survived']==0).mean()## pa2 - вероятность HEвыживания
pa2

np.float64(0.6161616161616161)

In [80]:
pab=df[df['Sex'] == 'female']['Survived'].mean()## pab - вероятность выживания  женщины
pab

np.float64(0.7420382165605095)

In [81]:
sur1=df[df['Pclass'] == 1]['Survived'].mean() ## вероятноость выживания 1-ого класса
sur1

np.float64(0.6296296296296297)

In [82]:
sur2=df[df['Pclass'] == 2]['Survived'].mean() ## вероятноость выживания  2-ого класса

In [83]:
sur3=df[df['Pclass'] == 3]['Survived'].mean() ## пвероятноость выживания  3-ого класса
sur3

np.float64(0.24236252545824846)

In [84]:
man=df[df['Sex'] == 'male']['Survived'].mean() ## процент выживших мужчин.
man

np.float64(0.18890814558058924)

In [85]:
fem=df[df['Sex'] == 'female']['Survived'].mean() ## процент выживших женщин
fem

np.float64(0.7420382165605095)

In [86]:
pb1a=df[df['Age'] <=25]['Survived'].mean() ## pb1a - вероятность выживания с возрастом до 25 лет
print(pb1a)
pb2a=df[(df['Age'] <= 50) & (df['Age'] >25)]['Survived'].mean()## pb2a - вероятность выживания с возрастом от 25 до 50 лет
print(pb2a)
pb3a=df[df['Age'] >50]['Survived'].mean()## pb2a - вероятность выживания с возрастом боллее 50 лет
print(pb3a)

0.4119601328903654
0.41260744985673353
0.34375

In [87]:
df['выживание по полу']=df["Sex"].apply(lambda x: fem if x =='female' else man)
df['выживание по классу']=df["Pclass"].apply(lambda x: sur1 if x ==1 else( sur2 if x ==2 else sur3))
df['выживание по возрасту']=df["Age"].apply(lambda x: pb1a if x<=25 else( pb3a if x>50 else pb2a))
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,выживание по полу,выживание по классу,выживание по возрасту
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0.188908,0.242363,0.411960
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0.742038,0.629630,0.412607
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.742038,0.242363,0.412607
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0.742038,0.629630,0.412607
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0.188908,0.242363,0.412607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0.188908,0.472826,0.412607
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0.742038,0.629630,0.411960
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0.742038,0.242363,0.412607
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0.188908,0.629630,0.412607
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0.188908,0.242363,0.412607

In [88]:
df.drop(['Cabin','Embarked','Ticket','Parch','Fare'],axis=1,inplace=True)

In [89]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,выживание по полу,выживание по классу,выживание по возрасту
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0.188908,0.242363,0.411960
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0.742038,0.629630,0.412607
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0.742038,0.242363,0.412607
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0.742038,0.629630,0.412607
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0.188908,0.242363,0.412607
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0.188908,0.472826,0.412607
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0.742038,0.629630,0.411960
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,0.742038,0.242363,0.412607
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0.188908,0.629630,0.412607
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0.188908,0.242363,0.412607

In [90]:
pb1a2=(df[df['Age'] <=25]['Survived']==0).mean() ## pb1a - вероятность выживания с возрастом до 25 лет
print(pb1a2)
pb2a2=(df[(df['Age'] <= 50) & (df['Age'] >25)]['Survived']==0).mean()## pb2a - вероятность выживания с возрастом от 25 до 50 лет
print(pb2a2)
pb3a2=(df[df['Age'] >50]['Survived']==0).mean()## pb2a - вероятность выживания с возрастом боллее 50 лет
print(pb3a2)

0.5880398671096345
0.5873925501432665
0.65625

In [91]:
df['Вероятность выживания']=df['выживание по полу']*df['выживание по классу']*df['выживание по возрасту']*pa
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,выживание по полу,выживание по классу,выживание по возрасту,Вероятность выживания
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0.188908,0.242363,0.411960,0.007240
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0.742038,0.629630,0.412607,0.073994
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0.742038,0.242363,0.412607,0.028482
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0.742038,0.629630,0.412607,0.073994
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0.188908,0.242363,0.412607,0.007251
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0.188908,0.472826,0.412607,0.014146
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0.742038,0.629630,0.411960,0.073878
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,0.742038,0.242363,0.412607,0.028482
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0.188908,0.629630,0.412607,0.018837
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0.188908,0.242363,0.412607,0.007251

In [92]:
df['Вероятность НЕвыживания']=(1-df['выживание по полу'])*(1-df['выживание по классу'])*(1-df['выживание по возрасту'])*pa2
df['delta']=df['Вероятность выживания']-df['Вероятность НЕвыживания']
df['prognoz']=df["delta"].apply(lambda x: 0 if x <0 else 1)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,выживание по полу,выживание по классу,выживание по возрасту,Вероятность выживания,Вероятность НЕвыживания,delta,prognoz
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0.188908,0.242363,0.411960,0.007240,0.222655,-0.215416,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0.742038,0.629630,0.412607,0.073994,0.034579,0.039415,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0.742038,0.242363,0.412607,0.028482,0.070736,-0.042253,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0.742038,0.629630,0.412607,0.073994,0.034579,0.039415,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0.188908,0.242363,0.412607,0.007251,0.222410,-0.215159,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0.188908,0.472826,0.412607,0.014146,0.154756,-0.140610,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0.742038,0.629630,0.411960,0.073878,0.034617,0.039261,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,0.742038,0.242363,0.412607,0.028482,0.070736,-0.042253,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0.188908,0.629630,0.412607,0.018837,0.108725,-0.089888,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0.188908,0.242363,0.412607,0.007251,0.222410,-0.215159,0

In [93]:
df2 = pd.read_csv('C:\\Users\\User\\Documents\\ДЗ\\test.csv') 
df2

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [95]:
df2['выживание по возрасту']=df["Age"].apply(lambda x: pb1a if x<=25 else( pb3a if x>50 else pb2a))
df2['выживание по полу']=df["Sex"].apply(lambda x: fem if x =='female' else man)
df2['выживание по классу']=df["Pclass"].apply(lambda x: sur1 if x ==1 else( sur2 if x ==2 else sur3))
df2

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,выживание по возрасту,выживание по полу,выживание по классу
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0.411960,0.188908,0.242363
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,0.412607,0.742038,0.629630
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0.412607,0.742038,0.242363
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0.412607,0.742038,0.629630
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,0.412607,0.188908,0.242363
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,0.412607,0.188908,0.472826
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,0.412607,0.188908,0.242363
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0.412607,0.742038,0.242363
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,0.412607,0.742038,0.472826
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,0.411960,0.742038,0.472826

In [96]:
df2['Вероятность выживания']=df2['выживание по полу']*df2['выживание по классу']*df2['выживание по возрасту']*pa
df2['Вероятность НЕвыживания']=(1-df2['выживание по полу'])*(1-df2['выживание по классу'])*(1-df2['выживание по возрасту'])*pa2
df2['delta']=df2['Вероятность выживания']-df2['Вероятность НЕвыживания']
df2['Survived']=df2["delta"].apply(lambda x: 0 if x <0 else 1)
df2

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,выживание по возрасту,выживание по полу,выживание по классу,Вероятность выживания,Вероятность НЕвыживания,delta,Survived
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0.411960,0.188908,0.242363,0.007240,0.222655,-0.215416,0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,0.412607,0.742038,0.629630,0.073994,0.034579,0.039415,1
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0.412607,0.742038,0.242363,0.028482,0.070736,-0.042253,0
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0.412607,0.742038,0.629630,0.073994,0.034579,0.039415,1
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,0.412607,0.188908,0.242363,0.007251,0.222410,-0.215159,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,0.412607,0.188908,0.472826,0.014146,0.154756,-0.140610,0
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,0.412607,0.188908,0.242363,0.007251,0.222410,-0.215159,0
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0.412607,0.742038,0.242363,0.028482,0.070736,-0.042253,0
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,0.412607,0.742038,0.472826,0.055567,0.049219,0.006348,1
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,0.411960,0.742038,0.472826,0.055479,0.049273,0.006206,1

In [97]:
prognoz=df2[['PassengerId','Survived']]
prognoz

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         1
4            896         0
..           ...       ...
413         1305         0
414         1306         0
415         1307         0
416         1308         1
417         1309         1

[418 rows x 2 columns]

In [99]:
prognoz.to_csv('C:\\Users\\User\\Documents\\ДЗ\\prognoz2.csv',index=False)